-- ==========================================================================================
-- TABLA: AGREEMENTS
-- Registro inmutable de cada acto de consentimiento otorgado por un titular de datos
-- Captura el consentimiento técnico (IP, user agent) y el documento legal vigente al momento 
-- PREVIOUS_AGREEMENTS_ID permite trazar la cadena de renovaciones o modificaciones
-- STATUS refleja el ciclo de vida del acuerdo: activo, revocado o expirado
-- ==========================================================================================
CREATE TABLE AGREEMENTS (
    ID                    UUID        PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    DATA_SUBJECT_ID       UUID        NOT NULL,
    TEMPLATE_ID           UUID        NOT NULL,
    TEMPLATE_VERSION      INTEGER     NOT NULL,
    DOCUMENT_ID           UUID        NOT NULL,
    STATUS                VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
                              CHECK (STATUS IN ('ACTIVE', 'REVOKED', 'EXPIRED')),
    IP_ORIGIN             INET,
    USER_AGENT            TEXT,
    EXPIRATION            TIMESTAMPTZ,
    PREVIOUS_AGREEMENTS_ID UUID,
    CREATED_AT            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    HASH_SHA256           VARCHAR(64),
    PREVIOUS_HASH_SHA256  VARCHAR(64)
);

ALTER TABLE AGREEMENTS ADD CONSTRAINT FK_AGREEMENT_SUBJECT
    FOREIGN KEY (DATA_SUBJECT_ID) REFERENCES DATA_SUBJECTS(ID) ON DELETE CASCADE;

ALTER TABLE AGREEMENTS ADD CONSTRAINT FK_AGREEMENT_TEMPLATE
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES(ID) ON DELETE RESTRICT;

ALTER TABLE AGREEMENTS ADD CONSTRAINT FK_AGREEMENT_DOCUMENT
    FOREIGN KEY (DOCUMENT_ID) REFERENCES PRIVACY_DOCUMENTS(ID) ON DELETE RESTRICT;

ALTER TABLE AGREEMENTS ADD CONSTRAINT FK_AGREEMENTS_PREVIOUS
    FOREIGN KEY (PREVIOUS_AGREEMENTS_ID) REFERENCES AGREEMENTS(ID) ON DELETE SET NULL;

CREATE INDEX IDX_AGREEMENTS_SUBJECT    ON AGREEMENTS (DATA_SUBJECT_ID);
CREATE INDEX IDX_AGREEMENTS_PREVIOUS   ON AGREEMENTS (PREVIOUS_AGREEMENTS_ID);
CREATE INDEX IDX_AGREEMENTS_STATUS_EXPIRATION ON AGREEMENTS (STATUS, EXPIRATION);