-- ==========================================================================================
-- TABLA: ENTITY_INTEGRITY_LOG
-- Registro de verificaciones de integridad sobre entidades maestras del sistema
-- Cubre finalidades, documentos, dominios y políticas de retención
-- Permite detectar alteraciones fuera del flujo normal de la aplicación
-- CREATED_BY es opcional: NULL en verificaciones automáticas, poblado en manuales
-- ==========================================================================================
CREATE TABLE ENTITY_INTEGRITY_LOG(
	ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	ENTITY_TYPE VARCHAR(50) NOT NULL, -- Purpose, Document, Domain, Retention_policy
		CHECK (ENTITY_TYPE IN ('PURPOSE', 'DOCUMENT', 'DOMAIN', 'RETENTION_POLICY')),
	ENTITY_ID UUID NOT NULL,
	STORED_HASH VARCHAR(64) NOT NULL,
	RECALCULATED_HASH VARCHAR(64) NOT NULL,
	IS_VALID BOOLEAN NOT NULL,
	CHECK_TYPE VARCHAR(20) NOT NULL
		CHECK(CHECK_TYPE IN ('SCHEDULED', 'MANUAL', 'ON_DEMAND')),
	CHECKED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	ERROR_DETAIL TEXT,
	CREATED_BY UUID,
	HASH_SHA256 VARCHAR(64),
	PREVIOUS_HASH_SHA256_ID VARCHAR(64)
);

ALTER TABLE ENTITY_INTEGRITY_LOG ADD CONSTRAINT FK_EIL_CREATED_BY
FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE SET NULL;

ALTER TABLE ENTITY_INTEGRITY_LOG ADD CONSTRAINT FK_EIL_PREVIOUS_HASH
FOREIGN KEY (PREVIOUS_HASH_SHA256_ID) REFERENCES ENTITY_INTEGRITY_LOG(HASH_SHA256) ON DELETE SET NULL;

CREATE INDEX IDX_EIL_ENTITY ON ENTITY_INTEGRITY_LOG(ENTITY_TYPE, ENTITY_ID);