-- ==========================================================================================
-- TABLA:PRIVACY_DOCUMENTS
-- Políticas de privacidad, términos y condiciones concernientes a los consentimientos
-- INMUTABLE: Esta tabla nunca se modifica, solo se versiona con nuevos documentos
-- ==========================================================================================
CREATE TABLE PRIVACY_DOCUMENTS (
	ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	TEMPLATE_KEY VARCHAR(100) NOT NULL, -- Único: POLITICA_PRIVACIDAD | TERMINOS Y CONDICIONES, 'Familia' del documento, 'Versión' dentro de la familia
	VERSION INTEGER NOT NULL DEFAULT 1,
	NAME VARCHAR(200) NOT NULL,
	URL_DOCUMENT VARCHAR(500) NOT NULL, -- Ruta de almacenamiento interno del documento
	HASH_SHA256 VARCHAR(64) NOT NULL, -- Integridad del documento (OBLIGATORIO),
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
	PUBLISH_AT TIMESTAMPTZ,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	CREATED_BY UUID,
	APPROVED_BY UUID,
	UNIQUE(TEMPLATE_KEY, VERSION),
	CHECK(TEMPLATE_KEY = UPPER(TEMPLATE_KEY))
);

CREATE UNIQUE INDEX UNIQUE_IS_ACTIVE_PER_TEMPLATE ON PRIVACY_DOCUMENTS (TEMPLATE_KEY) WHERE IS_ACTIVE = TRUE;

ALTER TABLE PRIVACY_DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS_CREATED_BY
FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE SET NULL;

ALTER TABLE PRIVACY_DOCUMENTS ADD CONSTRAINT FK_DOCUMENTS_APPROVED_BY
FOREIGN KEY (APPROVED_BY) REFERENCES USERS(ID) ON DELETE SET NULL;
