-- ==========================================================================================
-- TABLA: PURPOSE_REQUEST
-- Flujo de solicitud y aprobación para incorporar nuevas finalidad de tratamiento
-- Toda finalidad de tratamiento debe ser solicitada por el responsable de dominio y aprobada por el DPO/legal
-- PURPOSE_ID se llena solo al ser aprobada la solicitud, vinculando la finalidad creada
-- REVIEWED_AT permanece null hasta que el revisor actúe sobre la solicitud
-- ==========================================================================================
CREATE TABLE PURPOSE_REQUEST(
	ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	DOMAIN_ID UUID NOT NULL,
	REQUESTER_ID UUID NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	JUSTIFICATION TEXT NOT NULL,
	STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING'
		CHECK (STATUS IN ('PENDING', 'IN_REVIEW','APPROVED', 'REJECTED')),
	REVIEW_NOTES TEXT,
	REVIEWED_BY UUID,
	PURPOSE_ID UUID,
	REVIEWED_AT TIMESTAMPTZ,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE PURPOSE_REQUEST ADD CONSTRAINT FK_PR_DOMAIN
FOREIGN KEY (DOMAIN_ID) REFERENCES DOMAINS(ID) ON DELETE RESTRICT;

ALTER TABLE PURPOSE_REQUEST ADD CONSTRAINT FK_PR_REQUESTER
FOREIGN KEY (REQUESTER_ID) REFERENCES USERS(ID) ON DELETE RESTRICT;

ALTER TABLE PURPOSE_REQUEST ADD CONSTRAINT FK_PR_REVIEWER
FOREIGN KEY (REVIEWED_BY) REFERENCES USERS(ID) ON DELETE SET NULL;

ALTER TABLE PURPOSE_REQUEST ADD CONSTRAINT FK_PR_PURPOSE
FOREIGN KEY (PURPOSE_ID) REFERENCES PURPOSES(ID) ON DELETE SET NULL;
