-- ==========================================================================================
-- TABLA: PURPOSE_CHANGELOG
--
-- ==========================================================================================
CREATE TABLE PURPOSE_CHANGELOG(
	ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	PURPOSE_ID UUID NOT NULL,
	PURPOSE_VERSION_ID UUID NOT NULL,
	CHANGED_BY UUID,
	CHANGE_TYPE VARCHAR(30) NOT NULL
		CHECK (CHANGE_TYPE IN ('CREATED', 'UPDATED','ACTIVATED','DEACTIVATED','APPROVED','REJECTED')),
	FIELD_NAME VARCHAR(100),
	OLD_VALUE TEXT,
	NEW_VALUE TEXT,
	CHANGE_REASON TEXT,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE PURPOSE_CHANGELOG ADD CONSTRAINT FK_PCL_PURPOSE
FOREIGN KEY (PURPOSE_ID) REFERENCES PURPOSES(ID) ON DELETE CASCADE;

ALTER TABLE PURPOSE_CHANGELOG ADD CONSTRAINT FK_PLC_USER
FOREIGN KEY (CHANGED_BY) REFERENCES USERS(ID) ON DELETE SET NULL;

CREATE INDEX IDX_PCL_CREATED ON PURPOSE_CHANGELOG(CREATED_AT DESC);
CREATE INDEX IDX_PCL_PURPOSE ON PURPOSE_CHANGELOG(PURPOSE_ID);