-- ==========================================================================================
-- TABLA: PURPOSES
-- Catálogo de finalidades de tratamiento de datos
-- Define QUÉ se hace con los datos y con qué propósito
-- Requiere la aprobación del DPO + Legal antes de activar una nueva finalidad
-- ==========================================================================================
CREATE TABLE PURPOSES(
	ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	TEMPLATE_KEY VARCHAR(50) NOT NULL,
	VERSION INTEGER NOT NULL DEFAULT 1,
	DOMAIN_ID UUID,
	NAME VARCHAR(200) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	SHORT_DESCRIPTION VARCHAR(300) NOT NULL,
	REQUIRED BOOLEAN NOT NULL DEFAULT FALSE,
	REVOCABLE BOOLEAN NOT NULL DEFAULT TRUE,
	PRESENTATION_ORDER INTEGER NOT NULL DEFAULT 0,
		CHECK (PRESENTATION_ORDER >= 0),
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
	CHANGE_REASON TEXT,
	CREATED_BY UUID NOT NULL,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	APPROVED_BY UUID,
	APPROVED_AT TIMESTAMPTZ,
	HASH_SHA256 VARCHAR(64),
	PREVIOUS_HASH_SHA256 VARCHAR(64),

	CONSTRAINT UQ_PURPOSE_TEMPLATE_KEY_VERSION UNIQUE (TEMPLATE_KEY, VERSION)
);

CREATE UNIQUE INDEX UX_PURPOSE_TEMPLATE_KEY_ACTIVE ON PURPOSES (TEMPLATE_KEY) WHERE IS_ACTIVE = TRUE;

ALTER TABLE PURPOSES ADD CONSTRAINT FK_PURPOSES_CREATED_BY 
FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE SET NUL;

ALTER TABLE PURPOSES ADD CONSTRAINT FK_PURPOSES_DOMAIN
FOREIGN KEY (DOMAIN_ID) REFERENCES DOMAINS(ID);

ALTER TALE PURPOSES ADD CONSTRAINT FK_PURPOSES_APPROVED_BY
FOREIGN KEY (APPROVED_BY) REFERENCES USERS(ID) ON DELETE SET NULL;