-- ==========================================================================================
-- TABLA: TREATMENT_RECORDS
-- Registro general del tratamiento
--
-- ==========================================================================================
CREATE TABLE TREATMENT_RECORDS (
    ID                          UUID        PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    PURPOSE_ID                  UUID        NOT NULL,
    DATA_SUBJECT_ID             UUID,
    LEGAL_BASIS_CODE            VARCHAR(50) NOT NULL,
    LEGAL_JUSTIFICATION         TEXT        NOT NULL,
    STARTED_AT                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ENDED_AT                    TIMESTAMPTZ,
    CREATED_BY                  UUID        NOT NULL,
    TEMPLATE_ID                 UUID        NOT NULL,
    HASH_SHA256                 VARCHAR(64),
    PREVIOUS_HASH_SHA256        VARCHAR(64),
    PREVIOUS_TREATMENT_RECORDS_ID UUID
);

ALTER TABLE TREATMENT_RECORDS ADD CONSTRAINT FK_TR_PURPOSE
    FOREIGN KEY (PURPOSE_ID) REFERENCES PURPOSES(ID) ON DELETE RESTRICT;

ALTER TABLE TREATMENT_RECORDS ADD CONSTRAINT FK_TR_DATA_SUBJECT
    FOREIGN KEY (DATA_SUBJECT_ID) REFERENCES DATA_SUBJECTS(ID) ON DELETE RESTRICT;

ALTER TABLE TREATMENT_RECORDS ADD CONSTRAINT FK_TR_PREVIOUS
    FOREIGN KEY (PREVIOUS_TREATMENT_RECORDS_ID) REFERENCES TREATMENT_RECORDS(ID) ON DELETE SET NULL;

ALTER TABLE TREATMENT_RECORDS ADD CONSTRAINT FK_TR_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID) ON DELETE RESTRICT;

ALTER TABLE TREATMENT_RECORDS ADD CONSTRAINT FK_TR_TEMPLATE
    FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES(ID) ON DELETE RESTRICT;